#!/usr/bin/env python

# Copyright 2017 Open Source Robotics Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import rospy
from prius_msgs.msg import Control
from geometry_msgs.msg import Twist


class Translator:
    def __init__(self):
        self.sub = rospy.Subscriber("key_vel", Twist, self.callback)
        self.pub = rospy.Publisher('prius', Control, queue_size=1)
        self.last_published_time = rospy.get_rostime()
        self.last_published = None
        self.timer = rospy.Timer(rospy.Duration(1./20.), self.timer_callback)
        
    def timer_callback(self, event):
        if self.last_published and self.last_published_time < rospy.get_rostime() + rospy.Duration(1.0/20.):
            self.callback(self.last_published)

    def callback(self, message):
        rospy.logdebug("key_teleop_translator received twist %s, %s", message.linear, message.angular)
        command = Control()
        # command.header = message.header
        if message.linear.x > 0:
            command.throttle = message.linear.x
            command.brake = 0.0
            command.shift_gears = Control.FORWARD
        elif message.linear.x < 0:
            command.throttle = message.linear.x * -1
            command.brake = 0.0
            command.shift_gears = Control.REVERSE
        else:
            command.throttle = 0.0
            command.brake = 1.0
            command.shift_gears = Control.NEUTRAL

        command.steer = message.angular.z
        
        self.last_published = message
        self.pub.publish(command)

if __name__ == '__main__':
    rospy.init_node('key_teleop_translator')
    t = Translator()
    rospy.spin()
